# 这是 Noir 的配置文件
qq:
  # 机器人的QQ号
  botID: 3373794519
  # QQ管理账号
  admin:
    - 3337913379
  # QQ群号
  group: 557853118
  commands:
    list: '#ls'
    bind: '#绑定'
    execute: '/'
  # 绑定后执行的命令, 可以是添加白名单
  commands-after-bind:
    - 'wl add [player-name]'
  # 回复方式
  no-words:
    - '操你妈'
    - 'cnm'
    - '你妈死了'
    - 'nmsl'
# 不要修改此项
version: null
